# -*- coding: utf-8 -*-
"""Assignment -3 answers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ACZvbEM5hBI-3q_UiG0tfNUcu0hzefph

##1. Write a function to compute 5/0 and use try/except to catch the exceptions
"""

def divide():
    return 5/0

try:
    divide()
except ZeroDivisionError as ze:
    print("You entered number that non zero values")
except:
    print("Any other exception")

"""## 2.2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
"""

subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

# Use list comprehension instead of looping over each of the predicates
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)

